---
# tasks for IdP Restore
- name: "RESTORE - Retrieve MySQL backups"
  command: "{{ item }}"
  with_items:
   - "rsync -avzh {{ bck_uri }}/{{ fqdn }}/{{ host_bck_path }}/shibboleth_db.sql.gz {{ files_dir }}/{{ fqdn }}/idp/mysql-restore/shibboleth_db.sql.gz"
   - "rsync -avzh {{ bck_uri }}/{{ fqdn }}/{{ host_bck_path }}/statistics_db.sql.gz {{ files_dir }}/{{ fqdn }}/idp/mysql-restore/statistics_db.sql.gz"
  delegate_to: 127.0.0.1
  when:
    - bck_uri is defined
    - bck_uri != ""
    - host_bck_path is defined
    - host_bck_path != ""

- name: "RESTORE - Put 'shibboleth' and 'statistics' database backups in the '/root' directory"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "0600"
  with_items:
   - { src: "{{ files_dir }}/{{ fqdn }}/idp/mysql-restore/shibboleth_db.sql.gz", dest: "/root/shibboleth_db.sql.gz" }
   - { src: "{{ files_dir }}/{{ fqdn }}/idp/mysql-restore/statistics_db.sql.gz", dest: "/root/statistics_db.sql.gz" }

- name: "RESTORE - Extract 'shibboleth' and 'statistics' database backups"
  command: "gunzip {{ item }}"
  with_items:
   - "/root/shibboleth_db.sql.gz"
   - "/root/statistics_db.sql.gz"

- name: "RESTORE - Assign the right permissions to the 'shibboleth' and 'statistics' backup extracted"
  file:
   dest: "{{ item }}"
   owner: "root"
   group: "root"
   mode: "600"
  with_items:
   - "/root/shibboleth_db.sql"
   - "/root/statistics_db.sql"

- name: "RESTORE - DROP the existing 'shibboleth' and 'statistics' databases"
  mysql_db:
   name: "{{ item }}"
   state: absent
  with_items:
   - "shibboleth"
   - "statistics"

- name: "RESTORE - Restore 'shibboleth' and 'statistics' databases"
  mysql_db:
   encoding: "utf8"
   state: import
   name: all
   target: "{{ item }}"
  with_items:
   - "/root/shibboleth_db.sql"
   - "/root/statistics_db.sql"

- name: "RESTORE - Remove the backups restored from /root directory"
  file:
   dest: "{{ item }}"
   state: "absent"
  with_items:
   - "/root/shibboleth_db.sql"
   - "/root/statistics_db.sql"

- name: "RESTORE - Check if the HOST YAML file is encrypted with Vault"
  command: "cat {{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
  delegate_to: 127.0.0.1
  register: host_yaml

- name: "RESTORE - Descrypt Vaulted HOST YAML file"
  command: "ansible-vault decrypt --vault-password-file {{ vault_file }} {{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
  delegate_to: 127.0.0.1
  when: "'ANSIBLE_VAULT' in host_yaml.stdout"

- name: "RESTORE - Be sure to set 'idp_db_restore' to 'false'"
  lineinfile:
   path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
   regexp: '^idp_db_restore'
   line: 'idp_db_restore: "false"'
  delegate_to: 127.0.0.1

- name: "RESTORE - Encrypt HOST YAML file with Vault"
  command: "ansible-vault encrypt --vault-password-file {{ vault_file }} {{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
  delegate_to: 127.0.0.1
  when: "'ANSIBLE_VAULT' in host_yaml.stdout"
